Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  N = 3
  (1..N).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|
      machine.vm.hostname = "machine#{machine_id}"

      # Valid ranges can be modified in the /etc/vbox/networks.conf file. For
      # more information including valid format see:
      #  https://www.virtualbox.org/manual/ch06.html#network_hostonly
      machine.vm.network "private_network", ip: "192.168.56.#{20+machine_id}"

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "playbook.yml"
          ansible.host_vars = {
            "machine1" => {
              "kafka_broker_id" => 1,
              "zookeeper_myid" => 1},
            "machine2" => {
              "kafka_broker_id" => 2,
              "zookeeper_myid" => 2},
            "machine3" => {
              "kafka_broker_id" => 3,
              "zookeeper_myid" => 3},
          }

          ansible.groups = {
            "kafka" => ["machine[1:3]"],
            "zookeeper" => ["machine[1:3]"]
          }

        end
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2 
  end

end
