---
namespace: saiello
name: kafka
version: 0.0.5
readme: README.md
authors:
  - Simone Aiello <saiello@redhat.com>
description: Ansible collection to provision and manage Kafka and RedHat AMQ Streams
license_file: LICENSE
tags:
  - java
  - kafka
  - zookeeper
  - streams
  - amq
dependencies:
  middleware_automation.redhat_csp_download: ">=1.1.2"
repository: https://github.com/saiello/kafka
documentation: https://github.com/saiello/kafka
homepage: https://github.com/saiello/kafka
issues: https://github.com/saiello/kafka/issues
build_ignore:
  - molecule
  - .github
  - "*.tar.gz"
  - "*.tgz"
  - "*.zip"
  - venv
