---
- name: Check role parameters
  ansible.builtin.assert:
    that:
      - kafka_home is defined
      - kafka_broker_id is defined
    quiet: true

- name: Build kafka config
  saiello.kafka.kafka_config:
    config: "{{ __kafka_input_config }}"

- name: Debug kafka config
  ansible.builtin.debug: var={item}
  with_items:
    - __kafka_config
    - __admin_config

- name: Check kafka_inter_broker_listener_name is valid
  ansible.builtin.assert:
    that:
      - kafka_inter_broker_listener_name is defined
      - kafka_inter_broker_listener_name in __kafka_config.listeners
    msg: |
      kafka_inter_broker_listener_name is undefined or not valid. 
      Allowed values are: {{ __kafka_config.listeners.values() }}
    quiet: true

- name: Initialize kafka_java_opts
  ansible.builtin.set_fact:
    kafka_java_opts: "{{ kafka_java_opts | default([]) }}"