---
- name: Create admin config file
  ansible.builtin.template:
    src: admin.properties.j2
    dest: "{{ __kafka_admin_config }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0400
  when: 
    - __kafka_admin.require_command_config is defined
    - __kafka_admin.require_command_config
    