---
- name: Add kafka_java_opts
  ansible.builtin.set_fact:
    kafka_java_opts: "{{ kafka_java_opts + [
        '-Djava.security.auth.login.config=' + kafka_jaas_config_file_location
      ] }}"
  when: 
    - zookeeper_auth_client_enabled
    - zookeeper_auth_type is defined
    - zookeeper_auth_type == 'gssapi'

- name: Set SSL facts
  ansible.builtin.set_fact:
    kafka_ssl_truststore_file: "{{ kafka_tls_config.trustedCA.file }}"
    kafka_ssl_truststore_location: "{{ kafka_tls_config.trustedCA.location }}"
    kafka_ssl_keystore_file: "{{ kafka_tls_config.keystore.file }}"
    kafka_ssl_keystore_location: "{{ kafka_tls_config.keystore.location }}"
    kafka_ssl_keystore_password: "{{ kafka_tls_config.keystore.password }}"
    kafka_ssl_keystore_type: "{{ kafka_tls_config.keystore.type }}"
  when: 
  - kafka_tls_config is defined
  - kafka_tls_config.enabled

- name: Create security dir for Kafka
  ansible.builtin.file:
    path: "{{ kafka_home }}/security"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0755
  become: true

- name: Copy jaas config file
  ansible.builtin.template:
    src: "templates/jaas.conf.j2"
    dest: "{{ kafka_jaas_config_file_location }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0400
  when: 
    - zookeeper_auth_client_enabled
    - zookeeper_auth_type is defined
    - zookeeper_auth_type == 'gssapi'
  become: true

- name: Copy SSL resources
  block:
    - name: Copy truststore file
      ansible.builtin.copy:
        src: "{{ kafka_ssl_truststore_file }}"
        dest: "{{ kafka_ssl_truststore_location }}"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: 0400

    - name: Copy keystore file
      ansible.builtin.copy:
        src: "{{ kafka_ssl_keystore_file }}"
        dest: "{{ kafka_ssl_keystore_location }}"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: 0400
  when:
    - item.value.tls is defined
    - item.value.tls
  become: true

- name: Copy kerberos keytab file
  ansible.builtin.copy:
      src: "{{ kafka_kerberos_keytab_file }}"
      dest: "{{ kafka_kerberos_keytab_location }}"
      owner: "{{ kafka_user }}"
      group: "{{ kafka_group }}"
      mode: 0400
  when:
    - item.value.authentication.type is defined
    - item.value.authentication.type == 'gssapi'
  become: true