---
- name: Gather Zookeeper facts
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups[zookeeper_servers_ansible_group] }}"

- name: Init Zookeeper servers facts
  ansible.builtin.set_fact:
    zookeeper_gssapi_enabled: "{{ zookeeper_auth_type is defined and zookeeper_auth_type == 'gssapi' }}"
    zookeeper_tls_enabled: "{{ zookeeper_auth_type is defined and zookeeper_auth_type == 'tls' }}"
    zookeeper_servers: []

- name: Print Zookeeper server address
  ansible.builtin.debug:
    var: zookeeper_address_fact
    verbosity: 1

- name: Set Zookeeper servers facts
  ansible.builtin.set_fact:
    zookeeper_servers: "{{ zookeeper_servers + [{
          'myid': hostvars[item].zookeeper_myid,
          'address': zookeeper_gssapi_enabled | ternary(hostvars[item]['ansible_facts']['fqdn'], hostvars[item].ansible_facts[zookeeper_interface_name].ipv4.address),
          'client_port': zookeeper_tls_enabled | ternary(zookeeper_secure_client_port, zookeeper_client_port),
          'follower_port': 2888 + (zookeeper_port_offset | int),
          'election_port': 3888 + (zookeeper_port_offset | int)
        }]
    }}"
  with_items: "{{ groups[zookeeper_servers_ansible_group] }}"

- name: Print Zookeeper servers
  ansible.builtin.debug:
    var: zookeeper_servers
    verbosity: 1
